/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parcialdos;

import javax.swing.JOptionPane;

public class Pantalla extends javax.swing.JFrame {

    ParcialDos miLista = new ParcialDos();
    int idGlobal = 1;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pantalla.class.getName());

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSimular = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnEliminarID = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorial = new javax.swing.JTextArea();
        lblEstado = new javax.swing.JLabel();
        btnBuscarId = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnBajaVibracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSimular.setText("Simular sensores ");
        btnSimular.addActionListener(this::btnSimularActionPerformed);

        btnMostrar.setText("Mostrar historial");
        btnMostrar.addActionListener(this::btnMostrarActionPerformed);

        btnReporte.setText("Reporte estadistico");
        btnReporte.addActionListener(this::btnReporteActionPerformed);

        btnEliminarID.setText("Eliminar por id");
        btnEliminarID.addActionListener(this::btnEliminarIDActionPerformed);

        txtHistorial.setColumns(20);
        txtHistorial.setRows(5);
        jScrollPane1.setViewportView(txtHistorial);

        lblEstado.setText("Alerta en tiempo real:");

        btnBuscarId.setText("Buscar por id");
        btnBuscarId.addActionListener(this::btnBuscarIdActionPerformed);

        jButton1.setText("Buscar por sensor");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnBajaVibracion.setText("Baja Vibracion");
        btnBajaVibracion.addActionListener(this::btnBajaVibracionActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarID)
                            .addComponent(btnMostrar)
                            .addComponent(btnSimular)
                            .addComponent(btnBuscarId)
                            .addComponent(jButton1)
                            .addComponent(btnBajaVibracion))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReporte)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimular)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReporte)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBajaVibracion))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        String[] tipos = {"Temperatura", "Humedad", "Vibracion"};
        String tipo = tipos[(int) (Math.random() * 3)];
        double valor = (Math.random() * 150 - 20);
        int prioridad = 1;
        String etiqueta = "";

        if (tipo.equals("Temperatura")) {
            if (valor < -40 || valor > 120) {
                lblEstado.setText("TEMPERATURA CORRUPTA¡¡¡");
                return;
            }
        } else if (tipo.equals("Humedad")) {
            if (valor < 0 || valor > 100) {
                lblEstado.setText("HUMEDAD CORRUPTA¡¡¡");
                return;
            }
            if (valor > 90) {
                prioridad = 3;
                etiqueta = " - ALERTA DE INUNDACION";
            } else if (valor < 10) {
                prioridad = 2;
                etiqueta = " - ALERTA ELECTROESTATICA";
            }
        } else if (tipo.equals("Vibracion")) {
            if (valor > 7.1) {
                prioridad = 3;
            } else if (valor >= 4.6) {
                prioridad = 2;
            }
        }

        Nodo nuevo = new Nodo(idGlobal++, "SENS-" + (int) (Math.random() * 100), tipo, (float) valor, prioridad);

        miLista.insertar(nuevo);

        lblEstado.setText("Alerta generada!" + etiqueta);

        btnMostrarActionPerformed(evt);

    }//GEN-LAST:event_btnSimularActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        txtHistorial.setText("");

        Nodo aux = miLista.incio;

        if (aux == null) {
            txtHistorial.setText("La lista está vacía.");
            return;
        }

        while (aux != null) {

            String valorFormateado = String.format("%.2f", aux.valor);

            txtHistorial.append("ID: " + aux.id + " | " + aux.tipo + ": "
                    + valorFormateado + " | P: " + aux.prioridad + "\n");

            aux = aux.sig;
        }

    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        if (miLista.incio == null) {
            return;
        }

        float suma = 0;
        int criticas = 0, bajas = 0;
        Nodo aux = miLista.incio;

        while (aux != null) {
            suma += aux.valor;
            if (aux.prioridad == 3) {
                criticas++;
            }
            if (aux.prioridad == 1) {
                bajas++;
            }
            aux = aux.sig;
        }
        float promedio = suma / miLista.contador;
        txtHistorial.setText("--- REPORTE ---\n");
        txtHistorial.append("Promedio General: " + promedio + "\n");
        txtHistorial.append("Alertas Críticas: " + criticas + "\n");
        txtHistorial.append("Alertas Bajas: " + bajas + "\n");
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnEliminarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarIDActionPerformed
        String idBusca = javax.swing.JOptionPane.showInputDialog("Ingrese el ID a eliminar:");
        if (idBusca == null) {
            return; // Por si el usuario cancela
        }
        int idTarget = Integer.parseInt(idBusca);
        Nodo aux = miLista.incio;
        boolean encontrado = false;

        while (aux != null) {
            if (aux.id == idTarget) {

                if (aux == miLista.incio) {
                    miLista.eliminarPrimero();
                } else if (aux == miLista.fin) {
                    miLista.fin = aux.ant;
                    miLista.fin.sig = null;
                } else {
                    aux.ant.sig = aux.sig;
                    aux.sig.ant = aux.ant;
                }

                miLista.contador--;
                encontrado = true;
                lblEstado.setText("ID " + idTarget + " eliminado con éxito.");
                break;
            }
            aux = aux.sig;
        }

        if (!encontrado) {
            lblEstado.setText("Error: ID no encontrado.");
        }
    }//GEN-LAST:event_btnEliminarIDActionPerformed

    private void btnBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdActionPerformed
        String idBusca = javax.swing.JOptionPane.showInputDialog("Ingrese el ID del registro:");
        if (idBusca == null || idBusca.isEmpty()) {
            return;
        }

        int idTarget = Integer.parseInt(idBusca);
        Nodo aux = miLista.incio;
        boolean encontrado = false;

        while (aux != null) {
            if (aux.id == idTarget) {
                txtHistorial.setText("--- RESULTADO DE BÚSQUEDA ---\n");
                txtHistorial.append("ID: " + aux.id + "\nSensor: " + aux.sensorID
                        + "\nTipo: " + aux.tipo + "\nValor: " + aux.valor
                        + "\nPrioridad: " + aux.prioridad + "\n");
                encontrado = true;
                break;
            }
            aux = aux.sig;
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "El ID " + idTarget + " no existe.");
        }

    }//GEN-LAST:event_btnBuscarIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] opciones = {"Temperatura", "Humedad", "Vibracion"};
        String sensorABuscar = (String) javax.swing.JOptionPane.showInputDialog(
                this,
                "Seleccione el tipo de sensor para filtrar:",
                "Buscador por Sensor",
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]);

        if (sensorABuscar == null) {
            return;
        }

        txtHistorial.setText("--- RESULTADOS PARA: " + sensorABuscar.toUpperCase() + " ---\n");
        Nodo aux = miLista.incio;
        int encontrados = 0;

        while (aux != null) {
            if (aux.tipo.equals(sensorABuscar)) {
                txtHistorial.append("ID: " + aux.id
                        + " | Valor: " + String.format("%.2f", aux.valor)
                        + " | Prioridad: " + aux.prioridad + "\n");
                encontrados++;
            }
            aux = aux.sig;
        }

        if (encontrados == 0) {
            txtHistorial.append("No se encontraron registros de este tipo.");
        } else {
            txtHistorial.append("Total de alertas encontradas: " + encontrados);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBajaVibracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaVibracionActionPerformed
        txtHistorial.setText("--- ALERTAS VIBRACIÓN: PRIORIDAD BAJA ---\n");

        Nodo aux = miLista.incio;
        int contadorFiltro = 0;

        while (aux != null) {
            if (aux.tipo.equals("Vibracion") && aux.prioridad == 1) {
                txtHistorial.append("ID: " + aux.id
                        + " | Valor: " + String.format("%.2f", aux.valor)
                        + " | Estado: Seguro\n");
                contadorFiltro++;
            }

            aux = aux.sig;
        }

        if (contadorFiltro == 0) {
            txtHistorial.append("No hay alertas de vibración con prioridad baja.");
        } else {
            txtHistorial.append("\nSe encontraron " + contadorFiltro + " registros.");
        }


    }//GEN-LAST:event_btnBajaVibracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pantalla().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajaVibracion;
    private javax.swing.JButton btnBuscarId;
    private javax.swing.JButton btnEliminarID;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSimular;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTextArea txtHistorial;
    // End of variables declaration//GEN-END:variables
}
